###########
# Globals #
###########

stages:
  - Conan Test Build
  - Conan Recipe Upload
  - Conan Binary Upload

####################
# Conan Test Build #
####################

Linux/GCC Build:
  stage: Conan Test Build
  image: stabletec/build-core:fedora-gcc
  tags:
    - linux
    - docker
  dependencies: []
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=True

Linux/Clang Build:
  stage: Conan Test Build
  image: stabletec/build-core:fedora-clang
  tags:
    - linux
    - docker
  dependencies: []
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=True

CentOS/GCC Build:
  stage: Conan Test Build
  image: stabletec/build-core:centos-gcc
  tags:
    - linux
    - docker
  dependencies: []
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build missing -s build_type=Release -o *:shared=True

Windows/MSVC2017 Build:
  stage: Conan Test Build
  tags:
    - windows
    - msvc2017
  dependencies: []
  before_script:
    - call %MSVC2017_BUILD_TOOLS%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -s compiler.runtime=MTd -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -s compiler.runtime=MT -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -s compiler.runtime=MTd -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -s compiler.runtime=MT -o *:shared=False

.Windows/GCC Build:
  stage: Conan Test Build
  tags:
    - windows
    - gcc
  dependencies: []
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -o *:shared=True

.Windows/Clang Build:
  stage: Conan Test Build
  tags:
    - windows
    - clang
  dependencies: []
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build missing -s build_type=Release -o *:shared=True

#############################
# Conan Recipe Upload Stage #
#############################

Recipe Upload:
  stage: Conan Recipe Upload
  image: stabletec/alpine:conan
  only:
    - master
  tags:
    - linux
    - docker
  dependencies: []
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan export . $CONAN_USER/$CI_COMMIT_REF_NAME
    - conan upload -r $CONAN_REMOTE_NAME --confirm --force mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME
  after_script:
    - conan user --clean
    - conan remote remove $CONAN_REMOTE_NAME

#######################
# Conan Binary Upload #
#######################

Linux/GCC Package:
  stage: Conan Binary Upload
  image: stabletec/build-core:fedora-gcc
  only:
    - master
  tags:
    - linux
    - docker
  dependencies: []
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r $CONAN_REMOTE_NAME --confirm --check --all mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME
  after_script:
    - conan user --clean
    - conan remote remove $CONAN_REMOTE_NAME

Linux/Clang Package:
  stage: Conan Binary Upload
  image: stabletec/build-core:fedora-clang
  only:
    - master
  tags:
    - linux
    - docker
  dependencies: []
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r $CONAN_REMOTE_NAME --confirm --check --all mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME
  after_script:
    - conan user --clean
    - conan remote remove $CONAN_REMOTE_NAME

CentOS/GCC Package:
  stage: Conan Binary Upload
  image: stabletec/build-core:centos-gcc
  only:
    - master
  tags:
    - linux
    - docker
  dependencies: []
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update --not-export --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r $CONAN_REMOTE_NAME --confirm --check --all mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME
  after_script:
    - conan user --clean
    - conan remote remove $CONAN_REMOTE_NAME

Windows/MSVC2017 Package:
  stage: Conan Binary Upload
  only:
    - master
  tags:
    - windows
    - msvc2017
  dependencies: []
  before_script:
    - call %MSVC2017_BUILD_TOOLS%
    - conan remote add %CONAN_REMOTE_NAME% %CONAN_REMOTE_ADDRESS%
    - conan user -r %CONAN_REMOTE_NAME% -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MTd -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MT -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MTd -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MT -o *:shared=False
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  after_script:
    - conan user --clean
    - conan remote remove %CONAN_REMOTE_NAME%

.Windows/GCC Package:
  stage: Conan Binary Upload
  only:
    - master
  tags:
    - windows
    - gcc
  dependencies: []
  before_script:
    - conan remote add %CONAN_REMOTE_NAME% %CONAN_REMOTE_ADDRESS%
    - conan user -r %CONAN_REMOTE_NAME% -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  after_script:
    - conan user --clean
    - conan remote remove %CONAN_REMOTE_NAME%

.Windows/Clang Package:
  stage: Conan Binary Upload
  only:
    - master
  tags:
    - windows
    - clang
  dependencies: []
  before_script:
    - conan remote add %CONAN_REMOTE_NAME% %CONAN_REMOTE_ADDRESS%
    - conan user -r %CONAN_REMOTE_NAME% -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update --not-export --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  after_script:
    - conan user --clean
    - conan remote remove %CONAN_REMOTE_NAME%