# Required CI Environment Variables:
# CONAN_REMOTE_ADDRESS - The primary conan remote address to upload content to.
# CONAN_REMOTE_USER - The username to login to the remotes with.
# CONAN_REMOTE_PASSWORD - The password for the user to to login with.
# CONAN_USER - The name for use in the package declaration.

###########
# Globals #
###########

stages:
  - Build & Test
  - Stable Recipe Upload
  - Stable Binary Upload

################
# Build & Test #
################

# Templates #

.unix_build_template: &unix_build_template
  tags:
    - docker-linux
  script:
    - conan remote add -i 0 CI_Remote $CONAN_REMOTE_ADDRESS
    - conan create . $CONAN_USER/unstable --build outdated -s build_type=Debug
    - conan create . $CONAN_USER/unstable --build outdated -s build_type=Release

# Jobs #

CentOS6/GCC Unstable:
  stage: Build & Test
  image: stabletec/build-core:centos6-gcc
  <<: *unix_build_template

CentOS/GCC Unstable:
  stage: Build & Test
  image: stabletec/build-core:centos-gcc
  <<: *unix_build_template

CentOS/Clang Unstable:
  stage: Build & Test
  image: stabletec/build-core:centos-clang
  <<: *unix_build_template

Fedora/GCC Unstable:
  stage: Build & Test
  image: stabletec/build-core:fedora-gcc
  <<: *unix_build_template

Fedora/Clang Unstable:
  stage: Build & Test
  image: stabletec/build-core:fedora-clang
  <<: *unix_build_template

Windows/MSVC2017 Unstable:
  stage: Build & Test
  tags:
    - windows
    - msvc2017
  script:
    - conan remote add -i 0 CI_Remote --force ${env:CONAN_REMOTE_ADDRESS}
    - conan remove --outdated --force mariadb-connector-c/*@${env:CONAN_USER}/unstable
    - conan create . ${env:CONAN_USER}/unstable --build outdated -s build_type=Debug -s compiler.runtime=MDd
    - conan create . ${env:CONAN_USER}/unstable --build outdated -s build_type=Debug -s compiler.runtime=MTd
    - conan create . ${env:CONAN_USER}/unstable --build outdated -s build_type=Release -s compiler.runtime=MD
    - conan create . ${env:CONAN_USER}/unstable --build outdated -s build_type=Release -s compiler.runtime=MT

##############################
# Stable Recipe Upload Stage #
##############################

Recipe Upload Stable:
  stage: Stable Recipe Upload
  image: stabletec/conan:latest
  only:
    - tags
  tags:
    - docker-linux
  script:
    - conan remote add CI_Remote $CONAN_REMOTE_ADDRESS
    - conan remove --force mariadb-connector-c/*@$CONAN_USER/stable
    - conan export . $CONAN_USER/stable
    - conan user -r CI_Remote -p $CONAN_REMOTE_PASSWORD $CONAN_REMOTE_USER
    - conan upload -r CI_Remote --confirm mariadb-connector-c/*@$CONAN_USER/stable
  after_script:
    - conan user --clean

########################
# Stable Binary Upload #
########################

# Templates #

.unix_upload_template: &unix_upload_template
  only:
    - tags
  tags:
    - docker-linux
  script:
    - conan remote add -i 0 CI_Remote $CONAN_REMOTE_ADDRESS
    - conan create . $CONAN_USER/stable --update --not-export --build outdated -s build_type=Debug
    - conan create . $CONAN_USER/stable --update --not-export --build outdated -s build_type=Release
    - conan user -r CI_Remote -p $CONAN_REMOTE_PASSWORD $CONAN_REMOTE_USER
    - conan upload -r CI_Remote --confirm --check --all mariadb-connector-c/*@$CONAN_USER/stable
  after_script:
    - conan user --clean

# Jobs #

CentOS6/GCC Stable:
  stage: Stable Binary Upload
  image: stabletec/build-core:centos6-gcc
  <<: *unix_upload_template

CentOS/GCC Stable:
  stage: Stable Binary Upload
  image: stabletec/build-core:centos-gcc
  <<: *unix_upload_template

CentOS/Clang Stable:
  stage: Stable Binary Upload
  image: stabletec/build-core:centos-clang
  <<: *unix_upload_template

Fedora/GCC Stable:
  stage: Stable Binary Upload
  image: stabletec/build-core:fedora-gcc
  <<: *unix_upload_template

Fedora/Clang Stable:
  stage: Stable Binary Upload
  image: stabletec/build-core:fedora-clang
  <<: *unix_upload_template

Windows/MSVC2017 Stable:
  stage: Stable Binary Upload
  tags:
    - windows
    - msvc2017
  only:
    - tags
  script:
    - conan remote add -i 0 CI_Remote --force ${env:CONAN_REMOTE_ADDRESS}
    - conan remove --outdated --force mariadb-connector-c/*@${env:CONAN_USER}/stable
    - conan create . ${env:CONAN_USER}/stable --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MDd
    - conan create . ${env:CONAN_USER}/stable --update --not-export --build outdated -s build_type=Debug -s compiler.runtime=MTd
    - conan create . ${env:CONAN_USER}/stable --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MD
    - conan create . ${env:CONAN_USER}/stable --update --not-export --build outdated -s build_type=Release -s compiler.runtime=MT
    - conan user -r CI_Remote -p "${env:CONAN_REMOTE_PASSWORD}" ${env:CONAN_REMOTE_USER}
    - conan upload -r CI_Remote --confirm --check --all mariadb-connector-c/*@${env:CONAN_USER}/stable
  after_script:
    - conan user --clean