stages:
  - Test Build
  - Recipe
  - Packaging

.build_packages: &build_template
  stage: Test Build
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build outdated -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build outdated -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build outdated -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --build outdated -s build_type=Release -o *:shared=True

.upload_packages: &upload_template
  stage: Packaging
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update -ne --build outdated -s build_type=Debug -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update -ne --build outdated -s build_type=Debug -o *:shared=True
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update -ne --build outdated -s build_type=Release -o *:shared=False
    - conan create . $CONAN_USER/$CI_COMMIT_REF_NAME --update -ne --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r $CONAN_REMOTE_NAME --confirm --check -no recipe --all mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME

# Test Build Stage

Build Fedora/GCC:
  image: stabletec/build-core:fedora-gcc
  tags:
    - linux
    - docker
  <<: *build_template

Build Fedora/Clang:
  image: stabletec/build-core:fedora-clang
  tags:
    - linux
    - docker
  <<: *build_template

Build CentOS/GCC:
  image: stabletec/build-core:centos-gcc
  tags:
    - linux
    - docker
  <<: *build_template

Build Windows/MSVC2017:
  stage: Test Build
  tags:
    - windows
    - msvc2017
  before_script:
    - call %MSVC2017_BUILD_TOOLS%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -s compiler.runtime=MTd
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -s compiler.runtime=MT
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -s compiler.runtime=MTd
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -s compiler.runtime=MT

.Build Windows/GCC:
  stage: Test Build
  tags:
    - windows
    - gcc
  before_script:
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -o *:shared=True

.Build Windows/Clang:
  stage: Test Build
  tags:
    - windows
    - clang
  before_script:
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --build outdated -s build_type=Release -o *:shared=True

# Recipe Stage

Recipe Upload:
  stage: Recipe
  image: stabletec/build-core:fedora-gcc
  tags:
    - linux
    - docker
  before_script:
    - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_ADDRESS
    - conan user -r $CONAN_REMOTE_NAME -p $CONAN_PASSWORD $CONAN_USER
  script:
    - conan export . $CONAN_USER/$CI_COMMIT_REF_NAME
    - conan upload -r $CONAN_REMOTE_NAME --confirm --force mariadb-connector/*@$CONAN_USER/$CI_COMMIT_REF_NAME

# Packaging Stage

Upload Fedora/GCC:
  image: stabletec/build-core:fedora-gcc
  tags:
    - linux 
    - docker
  <<: *upload_template

Upload Fedora/Clang:
  image: stabletec/build-core:fedora-clang
  tags:
    - linux
    - docker
  <<: *upload_template

Upload CentOS/GCC:
  image: stabletec/build-core:centos-gcc
  tags:
    - linux
    - docker
  <<: *upload_template

Upload Windows/MSVC2017:
  stage: Packaging
  tags:
    - windows
    - msvc2017
  before_script:
    - conan user -r %CONAN_REMOTE_NAME% -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
    - call %MSVC2017_BUILD_TOOLS%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -s compiler.runtime=MTd
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -s compiler.runtime=MT
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -s compiler.runtime=MDd -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -s compiler.runtime=MTd
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -s compiler.runtime=MD -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -s compiler.runtime=MT
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check -no recipe --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%

.Upload Windows/GCC:
  stage: Packaging
  tags:
    - windows
    - gcc
  before_script:
    - conan user -r $CONAN_REMOTE_NAME -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -o *:shared=True 
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check -no recipe --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%

.Upload Windows/Clang:
  stage: Packaging
  tags:
    - windows
    - clang
  before_script:
    - conan user -r $CONAN_REMOTE_NAME -p "%CONAN_PASSWORD%" %CONAN_USER%
    - conan remove --force mariadb-connector*@%CONAN_USER%/%CI_COMMIT_REF_NAME%
  script:
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Debug -o *:shared=True
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -o *:shared=False
    - conan create . %CONAN_USER%/%CI_COMMIT_REF_NAME% --update -ne --build outdated -s build_type=Release -o *:shared=True
    - conan upload -r %CONAN_REMOTE_NAME% --confirm --check -no recipe --all mariadb-connector/*@%CONAN_USER%/%CI_COMMIT_REF_NAME%